### ISSUE TITLE
Potentially incorrect solution of PSet 2, Question 4, Part b

### ISSUE THREAD

**Issue by MatchesMalonee** [zyxue/stanford-cs229#10]
[Link to the pynb in question](https://github.com/zyxue/stanford-cs229/blob/master/Problem-set-2/4-Constructing-kernels.ipynb)

In the b part of the question, shouldn't the answer be that a kernel is not possible? Since Mercer's Theorem states that the one and only requirement for a function to be a kernel is that the any and all of its kernel matrices should be positive semidefinite. 

Difference of two symmetric PSD matrices is not always positive semidefinite (The only way to accomplish that is to ensure that the x<sup>T</sup>Kx=0, which will only occur when K1=K2).

Please correct me if I went wrong somewhere.

**Comment by zyxue** [comment]
Thank you for spotting this. I think it's a typo. Following "doesn't necessarily equals 0", I intended to say "so $K$ is not a kernel". I've corrected it: https://github.com/zyxue/stanford-cs229/commit/d695f7160b02d0990a5c6d870a6897fd2c49d8b6

**Comment by zyxue** [comment]
Hi @MatchesMalonee , I am closing the ticket now. If you have extra questions, please feel free to reopen it.
