### ISSUE TITLE
ps2 Q2

### ISSUE THREAD

**Issue by cong1989** [zyxue/stanford-cs229#11]
https://github.com/zyxue/stanford-cs229/blob/master/Problem-set-2/2-Model-calibration.ipynb

PS2 Q2(c)
Seems to me an L2 regularization would add a bias on the calibration. The theoretical estimation(left of the equation) would diverge from the empirical estimation from the samples if theta intercept was not 0. The result can be derived following the same path in Q2(a).

**Comment by zyxue** [comment]
Could you please write your answer and send a pull request?

**Comment by usherbob** [comment]
Same questions as  @cong1989 , I believe the equation in (a) could not hold when we add L2 regularization. @cong1989 , May we have a communication directly through e-mail, wechat, or whatever. I am new at machine learning, and really suffer doing this homework.

**Comment by zyxue** [comment]
Thank you for pointing my problems out. I have updated the notebooks. Please let me know if you find any extra problems.
