### ISSUE TITLE
PS2 Q1(c)

### ISSUE THREAD

**Issue by cong1989** [zyxue/stanford-cs229#12]
https://github.com/zyxue/stanford-cs229/tree/master/Problem-set-2
Adding a Gaussian Noise may work as it may make the input non-perfectly separable.

**Comment by zyxue** [comment]
Could you "Please add a link to the notebook you are referring to" as instructed in the template for your questions?

**Comment by cong1989** [comment]
https://github.com/zyxue/stanford-cs229/tree/master/Problem-set-2

**Comment by zyxue** [comment]
You asked three questions in the last 15 min. Could you add a link to all of them? Also, Not sure if you are asking a question or just providing a comment, can you be more concrete and provide more details about what you are asking.

**Comment by usherbob** [comment]
ummm, ps2 1(c), adding Gaussian noise could make dataset B converge on Logistic Regression model, where you give your answer"No, not for sure".

**Comment by zyxue** [comment]
Thank you for pointing that out. I've updated the answer.
