### ISSUE TITLE
PS2 5

### ISSUE THREAD

**Issue by cong1989** [zyxue/stanford-cs229#13]
https://github.com/zyxue/stanford-cs229/blob/master/Problem-set-2/5-Kernelizing-the-perceptron.ipynb

Kernel only performs on original space. The point of using kernel is to avoid the complication of actually looking for the space projection. Easy question, but it would be nice to correct this one just for the sake of completeness.

**Comment by zyxue** [comment]
Could you please clarify what you meant?

**Comment by wxx07** [comment]
I have 2 questions about the same place.1) Isn't that K(x,z) already stands for the inner product between phi(x) and phi(z)? 2) how do you compute( here I retain the superscripts only) K(1,2) using your kernelized algorithm?

**Comment by zyxue** [comment]
Thank you for drawing my attention to the problem. I realized I had typo in PS2 5 (c), and I have corrected them.

Hi @wxx07, 

For your first question, it is an inner product between \theta and phi(x). 

I don't quite understand your second question.
