### ISSUE TITLE
PS2 Q4

### ISSUE THREAD

**Issue by Jaic1** [zyxue/stanford-cs229#15]
At https://github.com/zyxue/stanford-cs229/blob/master/Problem-set-2/4-Constructing-kernels.ipynb

It seems your answers for (f) and (h) are wrong.

<img src="https://latex.codecogs.com/gif.latex?for&space;\;&space;\left&space;(&space;f&space;\right&space;),&space;\;&space;we&space;\;&space;have&space;\&space;\sum_{i}^{&space;}&space;\left&space;(&space;z_{i}&space;f\left&space;(&space;x^{\left&space;(&space;i&space;\right&space;)}&space;\right&space;)&space;\right&space;)^{2}&space;." title="for \; \left ( f \right ), \; we \; have \ \sum_{i}^{ } \left ( z_{i} f\left ( x^{\left ( i \right )} \right ) \right )^{2} ." />

<img src="https://latex.codecogs.com/gif.latex?\large&space;for&space;\;&space;\left&space;(&space;h&space;\right&space;),&space;\;&space;we&space;\;&space;have&space;\&space;K\left&space;(&space;x,z&space;\right&space;)=&space;a_{0}&plus;a_{1}*K_{1}\left&space;(&space;x,z&space;\right&space;)&plus;...&plus;a_{n}*K_{1}^{n}\left&space;(&space;x,z&space;\right&space;)&space;,\&space;where&space;\;&space;a_{i}&space;\;&space;are&space;\;&space;positive&space;\;&space;coefficients.\\&space;Then,\;&space;using&space;\left&space;(&space;a&space;\right&space;)\left&space;(&space;c&space;\right&space;)\left&space;(&space;e&space;\right&space;),&space;\;&space;we&space;\;&space;can&space;\;&space;prove&space;\;&space;\left&space;(&space;h&space;\right&space;)." title="\large for \; \left ( h \right ), \; we \; have \ K\left ( x,z \right )= a_{0}+a_{1}*K_{1}\left ( x,z \right )+...+a_{n}*K_{1}^{n}\left ( x,z \right ) ,\ where \; a_{i} \; are \; positive \; coefficients.\\ Then,\; using \left ( a \right )\left ( c \right )\left ( e \right ), \; we \; can \; prove \; \left ( h \right )." />

**Comment by zyxue** [comment]
Great, thank you so much for pointing them out. I have corrected my mistakes.
