### ISSUE TITLE
Question about ps1 3(c)

### ISSUE THREAD

**Issue by usherbob** [zyxue/stanford-cs229#16]
https://github.com/zyxue/stanford-cs229/blob/master/Problem-set-1/3-Gaussian-discriminant-analysis.ipynb
When you get the estimate of sigma with maximum-likelihood method, why could we use the derivation of l to inverse(sigma), it does not make sense.

**Comment by zyxue** [comment]
Thank you for pointing out the issue. I have updated the notebook to make it more explicit that 

> the first equality used the property that the determinant of inverse is equal to the inverse of determinant.

i.e. det(A^{-1}) = 1 / det(A)
