### ISSUE TITLE
problem_set_1,5(b),where can i get the dataset?

### ISSUE THREAD

**Issue by aloha000** [zyxue/stanford-cs229#21]
[Please add a link to the notebook you are referring to]
https://github.com/zyxue/stanford-cs229/blob/master/Problem-set-1/ps1.pdf
the link in your pdf is not available, is it just my problem or the website is not available now?
many thanks!

**Comment by zyxue** [comment]
which link, is this what you want, https://github.com/zyxue/stanford-cs229/tree/master/Problem-set-1/data?

**Comment by zyxue** [comment]
Closed for long-time inactivity, feel free to reopen.
