### ISSUE TITLE
Problem Set 2, Question 4, Part e

### ISSUE THREAD

**Issue by Vrroom** [zyxue/stanford-cs229#22]
Hello!

In this section, you write K = K1*K2. I think that is incorrect because The i,j entry of K will be K1_(i,j)*K2_(i,j) and not what you would get if you simply multiplied the two matrices. 

https://github.com/zyxue/stanford-cs229/blob/master/Problem-set-2/4-Constructing-kernels.ipynb

Thanks

**Comment by zyxue** [comment]
You're absolutely right! K1*K2 isn't a matrix multiplication.I've corrected it.

Thank you for reporting!

**Comment by Vrroom** [comment]
You are welcome! Some of your solutions were quite helpful to me. And of course, thanks for providing the data! 
With regards to this question, I guess I'm being nit-picky but even now, I don't think that the proof handles the case for infinite feature vector. Unfortunately, even I haven't been able to come up with a satisfactory argument for this case.

**Comment by zyxue** [comment]
For the infinite case, check out this answer, https://stats.stackexchange.com/a/239530/112141. I thought it generalized to infinite vectors naturally, when d_1 -> inf and d_2 -> inf
