### ISSUE TITLE
Some problem about Problem Set 3, for the question --- A simple nerual network. 

### ISSUE THREAD

**Issue by alance123** [zyxue/stanford-cs229#23]
[Please add a link to the notebook you are referring to]

Hi, @zyxue , for the following problem:
       Let the activation functions for h1; h2; h3 be the linear function f(x) = x
and the activation function for o be the same step function as before. Is there a
specic set of weights that will make the loss 0? If yes, please explicitly state a value
for every weight. If not, please explain your reasoning.( https://github.com/zyxue/stanford-cs229/blob/master/Problem-set-3/1-A-simple-neural-network.ipynb )

I think the anwser is yes.  There is a
specic set of weights that will make the loss 0. Clearly, there are 3 lines corresponding to the 3 sides of the triangle, we can choose weights such that for the points in the triangle, h1, h2, h3<0; while for the  points out of the triangle, h1, h2, h3>0. Therefore, using the step function f(h1+h2+h3) can solve the problem. Is this right?

**Comment by zyxue** [comment]
Do you mean Problem Set 3 (b)? The answer is yes and the weights are in the matrix.

**Comment by alance123** [comment]
No, Problem Set 3 (c).

**Comment by zyxue** [comment]
Then the answer is NO as I explained in my notebook. Although each of the three lines are linear, but the together form a nonlinear boundary. Since the activation function is linear, f(x) = x, so the whole network just perform a linear transformation, thus it's not possible to create a nonlinear decision boundary.
