### ISSUE TITLE
ps4 5(a)

### ISSUE THREAD

**Issue by YunPengZ** [zyxue/stanford-cs229#24]
[ps4 5(a)](https://github.com/zyxue/stanford-cs229/blob/master/Problem-set-4/5-Markov-decision-processes.ipynb)
Hi, @zyxue , for the answer of ps4 5(a).
**The 1st inequality the following part has a  mistake**,in which ∑s′∈Sps+a1(s′)V1(s′) gets a larger value than  ∑s′∈Sps+a2(s′)V1(s′).So it should be >= ,right?
|||B(V1)−B(V2)||||∞=||B(V1)(s+)−B(V2)(s+)||
=B(V1)(s+)−B(V2)(s+)
=γ(maxa∈A∑s′∈Sps+a(s′)V1(s′)−maxa∈A∑s′∈Sps+a(s′)V2(s′))
=γ(∑s′∈Sps+a1(s′)V1(s′)−∑s′∈Sps+a2(s′)V2(s′))
=γ∑s′∈S(ps+a1(s′)V1(s′)−ps+a2(s′)V2(s′))
**≤γ∑s′∈S(ps+a2(s′)V1(s′)−ps+a2(s′)V2(s′))**
=γ∑s′∈Sps+a2(s′)(V1(s′)−V2(s′))
≤γ(V1(s∗)−V2(s∗))

**Comment by zyxue** [comment]
No, as I explained in the bullet point:
>The 1st inequality is a result of maxa∈A, change a1 to a2 will make ∑s′∈Sps+a(s′)V1(s′) smaller
