### ISSUE TITLE
PS4 1(b)

### ISSUE THREAD

**Issue by jzxl629** [zyxue/stanford-cs229#25]
The question says I need to add the regularization term to the loss function, and I wonder how you did that in the back_prop_regularized. Specifically I don't get the following section of the code in backward_prop:
if lamb > 0:
        gradW2 += lamb * W2
        gradW1 += lamb * W1

**Comment by zyxue** [comment]
If I recall correctly, you just take the derivates w.s.t W1 and W2 for the regularization part of the loss function
