### ISSUE TITLE
[IMPORTANT] Please consider taking down your CS229 solutions

### ISSUE THREAD

**Issue by cwolffff** [zyxue/stanford-cs229#29]
Dear Zhuyi,

Hello from the CS229 Course Staff. We have found that you posted solutions to past CS229 assignments on your publicly visible repo, and we kindly ask that you take it down or make it private immediately.

It is a violation of the Stanford Honor Code for students to search for and look at your solutions, and it is also a violation of the Honor Code for students to post their solutions online. As course staff, it is our duty to report students for suspected violations and we have already found students whom we suspect have copied from online solutions like yours.

Students who violate the Honor Code face serious negative consequences such as grading sanctions and being suspended from Stanford, and thus we would like to make sure that students cannot access solutions online easily. Please take your solutions down or make them private so that our students do not jeopardize their academic careers by referring to them.

All the best,
Christopher Wolff (CS229 TA)

**Comment by zyxue** [comment]
Hi Christopher, 

Thank you for reaching out. I initially put my repo up for knowledge-sharing purposes only as I have also learned a lot from reading others' solutions. But your concern makes sense and I will make it private.

Best,
Zhuyi

**Comment by zyxue** [comment]
Hey Chris, I wonder how come Stanford publishes the answers itself, too? 

https://see.stanford.edu/materials/aimlcs229/ps1_solution.pdf
https://see.stanford.edu/materials/aimlcs229/ps2_solution.pdf
https://see.stanford.edu/materials/aimlcs229/ps3_solution.pdf
https://see.stanford.edu/materials/aimlcs229/ps4_solution.pdf

**Comment by cwolffff** [comment]
Hi Zhuyi,

I just saw that your repository is public again. No worries if this was done by mistake, but we’d appreciate if you could make it private again.

Best,
Chris

—
Christopher Wolff
***@***.******@***.***>



On Apr 6, 2022, at 8:15 PM, Zhuyi Xue ***@***.******@***.***>> wrote:



Hi Christopher,

Thank you for reaching out. I initially put my repo up for knowledge-sharing purposes only as I have also learned a lot from reading others' solutions. But your concern makes sense and I will make it private.

Best,
Zhuyi
