### ISSUE TITLE
PS3 3(c)

### ISSUE THREAD

**Issue by qiang951128743** [zyxue/stanford-cs229#4]
please refer to https://github.com/stallmanifold/cs229-machine-learning-stanford-fall-2016/blob/master/homeworks/ps4_key.pdf for the correct answer.
One thing to note is that we only know the current parameters and x(pr), y(pr) and z(pr) are unknown. I do admire that you carried on the calculation to the end, I would definitely have given up.

**Comment by haroldmei** [comment]
Actually x^(or) is the observed training data, so it is known.

**Comment by zyxue** [comment]
Is that why you closed it, @qiang951128743 ? Thanks.
