### ISSUE TITLE
data for PS 2 - Q6

### ISSUE THREAD

**Issue by shivmeev** [zyxue/stanford-cs229#7]
I have been reviewing your solution for CS229. Thanks for uploading them here.
I was wondering if you can possibly upload data for PS 2.6. I cannot access it anymore through CS229 webpage. I really appreciate it.

**Comment by zyxue** [comment]
Hi @shivmeev, this particular piece of data isn't too big, so I added them as requested.

**Comment by shivmeev** [comment]
Thanks a bunch! :)
