### ISSUE TITLE
Question about Problem-set-1/1-Logistic-regression.ipynb

### ISSUE THREAD

**Issue by raoqiyu** [zyxue/stanford-cs229#8]
Notebook: https://github.com/zyxue/stanford-cs229/blob/master/Problem-set-1/1-Logistic-regression.ipynb

![image](https://user-images.githubusercontent.com/4653325/40828218-9fb99992-65b2-11e8-95d9-7c0c9b592cc5.png)

In the above picture，is the range of i and j should be n in the first line ?

**Comment by zyxue** [comment]
No, m is the number of data points in the dataset, and n is the number of dimensions of each data point.

**Comment by raoqiyu** [comment]
Why the range of i is different between the first line and the second line?

**Comment by zyxue** [comment]
I think you are right. Sorry, I missed the error myself.

For the record, I worked out the dimensions of all the variables.
x<sup>(i)</sup>: n × 1
θ: n × 1
H: n x n
z: n × 1

* m is the number of data points, that's it about m. 
* n is the number of features of each data point.

I've updated the [corresponding notebook](https://github.com/zyxue/stanford-cs229/blob/master/Problem-set-1/1-Logistic-regression.ipynb) now. Thank you very much for reporting!

**Comment by raoqiyu** [comment]
Thank you.
