### ISSUE TITLE
ps0 last question improvement

### ISSUE THREAD

**Issue by Lastcysa** [zyxue/stanford-cs229#9]
In regard to [ps0](https://github.com/zyxue/stanford-cs229/blob/master/Problem-set-0.ipynb) last question, you don't have to deal with the sum and claim the result by saying "all $\lambda_i$ should be $\ge 0$", which seems a bit weird in math. You have to include independence between all $\lambda_i$'s further in this case (though obvious). 

A better way is to deal with some arbitrary $i$, and apply the result in part (a):

$\forall i,0 \leq u^{{(i)}^T}Au^{(i)} = u^{{(i)}^T}\lambda_i u^{(i)} = \lambda_i ||u^{(i)}||^2$

**Comment by zyxue** [comment]
Thanks, but why $0 \leq \lambda_i ||u^{(i)}||^2$ for any $i$ without mention of sum?

**Comment by Lastcysa** [comment]
For any $i$, u^{(i)} is a n-dim vector, hence by the PSD property of A we have $0 \leq u^{{(i)}^T}Au^{(i)}$. Further by the eigenpair relationship proved in (a) you get the result.

**Comment by Lastcysa** [comment]
In your solution you're multiplying an arbitrary $x$ vector on LHS, thus resulting in the summation on RHS. But because the PSD property applies to all vectors, it is simpler to use an eigenvector so that the eigenpair property can be applied and hence all other eigenvalues' influence on that eigenvector is eliminated. Therefore you don't have a sum.

**Comment by zyxue** [comment]
I am not that strong in linear algebra. Could you please clarify what do you mean by "PSD property" and that "it applies to all vectors"?

**Comment by Lastcysa** [comment]
The most important property of any semi-positive definite (PSD) matrix A is that for any vector x, we have **x^TAx >=0**. Since any u(i) is a vector, we can plug any u(i) in that property, without loss of generality.

**Comment by zyxue** [comment]
Awesome! I get it now. Thanks, I've updated the corresponding notebook.

**Comment by Lastcysa** [comment]
Thanks. Your work is great overall. I'm closing this issue.
